project:
  type: website
  output-dir: docs

website:
  title: "Data Mining Course"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - modules.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

